"""Publish final video to GitHub Releases (free CDN).
Uses the GitHub API to create a release with the MP4 as a downloadable asset.
"""
import os
import json
import requests
from .utils import log, env, retry


def publish_to_release(
    video_path: str,
    title: str,
    description: str,
    repo: str = None,
    token: str = None,
    tag: str = None,
) -> str:
    """Create a GitHub Release and upload the MP4. Returns the asset URL."""
    repo = repo or env("GITHUB_REPOSITORY")
    token = token or env("GITHUB_TOKEN")
    if not repo or not token:
        log.warning("GITHUB_REPOSITORY/TOKEN not set, skipping publish")
        return ""

    if tag is None:
        from datetime import datetime
        tag = f"video-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"

    log.info(f"📤 Publishing to GitHub release: {repo} @ {tag}")

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }

    # Create release
    def create_release():
        r = requests.post(
            f"https://api.github.com/repos/{repo}/releases",
            headers=headers,
            json={
                "tag_name": tag,
                "name": title[:120],
                "body": description[:2000] + "\n\n_Generated by [FreeFlow](https://github.com/yourname/freeflow)_",
                "draft": False,
                "prerelease": False,
            },
            timeout=30,
        )
        if r.status_code == 422 and "already_exists" in r.text:
            # Tag exists — fetch existing
            r2 = requests.get(
                f"https://api.github.com/repos/{repo}/releases/tags/{tag}",
                headers=headers,
                timeout=30,
            )
            r2.raise_for_status()
            return r2.json()
        r.raise_for_status()
        return r.json()

    release = retry(create_release, retries=2)
    upload_url = release["upload_url"].split("{")[0]

    # Upload asset
    asset_name = f"{title[:50].replace(' ', '_').replace('/', '-')}.mp4"
    log.info(f"⬆️ Uploading {asset_name} ({os.path.getsize(video_path)/1024/1024:.1f} MB)...")

    with open(video_path, "rb") as f:
        def upload():
            return requests.post(
                upload_url,
                params={"name": asset_name, "label": title[:100]},
                headers={**headers, "Content-Type": "application/octet-stream"},
                data=f.read(),
                timeout=300,
            )
        resp = retry(upload, retries=2)

    if resp.status_code >= 300:
        log.error(f"Upload failed: {resp.status_code} {resp.text[:200]}")
        return ""

    asset = resp.json()
    log.info(f"✅ Published: {asset['browser_download_url']}")
    return asset["browser_download_url"]


def update_video_index(video_url: str, title: str, topic: str, out_path: str = "videos.json"):
    """Append a video record to videos.json for the web UI to display."""
    data = []
    if os.path.exists(out_path):
        try:
            with open(out_path) as f:
                data = json.load(f)
        except Exception:
            data = []
    data.insert(0, {
        "url": video_url,
        "title": title,
        "topic": topic,
        "timestamp": __import__("datetime").datetime.utcnow().isoformat() + "Z",
    })
    data = data[:50]  # keep last 50
    with open(out_path, "w") as f:
        json.dump(data, f, indent=2)


if __name__ == "__main__":
    print("publish module loaded. Use via md_to_video.py")
